repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: check-yaml
      - id: end-of-file-fixer
        exclude: '\.rs$'
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        stages: [pre-commit]
        entry: cargo +nightly fmt
      - id: clippy
        stages: [pre-commit]
        args:
          [--all-targets, --all, --, -D, clippy::all, -D, warnings, --no-deps]
  - repo: local
    hooks:
      - id: cargo-test
        name: Run cargo test
        entry: cargo test --all --
        language: system
        pass_filenames: false
        stages: [pre-push]
        types: [rust]
